"""Push-driven coordinator for Intratone doorbell calls.

The SIP INVITE is **deferred** until the user actually interacts (taps live
view in HomeKit, or taps Unlock). This matches the Cogelec Android app, which
launches `NotificationCallActivity` (UI only, no SIP) on FCM push and only
fires the INVITE when the user taps "Pick Up" in `CallActivity`. Doing it
this way means the doorbell hardware's ~19s call timeout doesn't start
ticking while the user is still racing to see the HomeKit notification.
"""

from __future__ import annotations

import asyncio
import dataclasses
import logging
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import TYPE_CHECKING

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator

from .const import DOMAIN

if TYPE_CHECKING:
    from .call_manager import CallManager
    from .rest_api import IntratoneAPI

_LOGGER = logging.getLogger(__name__)

# How long to wait for the audio bridge to come up after triggering the lazy
# INVITE. Covers TCP connect + INVITE→200 OK round-trip (~2 s) plus ffmpeg's
# VP8 keyframe wait (up to 15 s — see audio_bridge._FFMPEG_PUSH_READY_TIMEOUT_S).
_STREAM_READY_TIMEOUT_S = 20.0


@dataclass
class CallState:
    """A single doorbell call event.

    `ring_seq` is a monotonic counter; entities use it to detect new rings
    rather than a transient flag (which would race with state writes).
    `stream_url` is set once the SIP call is confirmed and audio bridge up,
    None before that and after hang-up.
    """

    call_id: str
    door_name: str
    caller_login: str
    received_at: datetime
    ring_seq: int
    stream_url: str | None = None
    # DTMF-like code from the FCM `codes` field — passed to `opendoor:<code>`
    # in the in-dialog SIP MESSAGE that actually triggers the relay. Defaults
    # to `*` (the most common Intratone setup).
    door_code: str = "*"
    # Physical door identifier (`NBPORTE` in the FCM payload). Useful for
    # multi-door installs (street door vs apartment door vs garage gate).
    door_number: str = ""


@dataclass
class _PendingInvite:
    """SIP/REST credentials parked at FCM push time, used when the user
    actually interacts. Mirrors what `NotificationCallActivity` would have
    in its Intent extras until the user taps Pick Up."""

    fcm_call_id: str
    target_uri: str
    target_host: str
    sip_username: str
    sip_password: str
    started: bool = False
    answer_called: bool = False
    # Set when the audio bridge is up and `stream_url` is on `CallState`.
    # Camera/Lock entities await this before talking to HomeKit.
    stream_ready: asyncio.Event = field(default_factory=asyncio.Event)


class IntratoneCoordinator(DataUpdateCoordinator[CallState | None]):
    """Coordinator that holds the latest call and notifies entities on push."""

    def __init__(
        self,
        hass: HomeAssistant,
        entry: ConfigEntry,
        api: IntratoneAPI,
    ) -> None:
        super().__init__(
            hass,
            _LOGGER,
            name=f"{DOMAIN}_{entry.entry_id}",
            update_interval=None,  # push-driven only
        )
        self.entry = entry
        self.api = api
        self._ring_seq = 0
        self._call_manager: CallManager | None = None
        # FCM and SIP have independent call IDs (the former comes from the
        # Intratone REST API and feeds /answer; the latter is generated by us
        # for the SIP dialog). We remember the SIP one here so the audio
        # bridge's on_call_active callback can match its arg against ours.
        self._active_sip_call_id: str | None = None
        self._pending: _PendingInvite | None = None

    def attach_call_manager(self, call_manager: CallManager) -> None:
        """Wire the SIP/audio orchestrator in after construction."""
        self._call_manager = call_manager

    async def _async_update_data(self) -> CallState | None:
        return self.data

    async def async_handle_push(self, payload: dict) -> None:
        """FCM push handler.

        Stores SIP creds + fires the HomeKit doorbell event so the iPhone
        rings. Does NOT open the SIP dialog — that happens lazily when the
        user taps live view or Unlock.

        Cogelec emits several payload shapes — the historical `call_id` +
        `message` ring, the newer `TYPE=24` form keyed on
        `NOTIFICATION_UUID`, plus `notif_type` routed events (`callCancel`,
        `unregister`, …). We dispatch each to its specific handler and
        ignore the rest.
        """
        notif_type = payload.get("notif_type")

        # Visitor walked away before any device picked up — Cogelec sends a
        # cancel push so the historical ring becomes invalid. Tear down any
        # in-progress call and clear `_pending` so the iPhone tile won't
        # try to fetch a dead stream. The iOS doorbell notification itself
        # is Apple-managed; we can't dismiss it remotely, but the user no
        # longer wastes a tap on a stale call.
        if notif_type == "callCancel" or (
            "cancel" in payload and notif_type is None
        ):
            await self._async_handle_call_cancel(payload)
            return

        # Server-side credential invalidation (account reset, building
        # operator unbound this device, …). Re-pair flow is mostly silent
        # since we keep the stored phone/device_id, but trigger HA's auth
        # repair so the user sees a notification if the silent refresh
        # also fails.
        if notif_type == "unregister" or "unregister" in payload:
            _LOGGER.warning(
                "Received unregister push from Intratone — starting reauth flow"
            )
            self.entry.async_start_reauth(self.hass)
            return

        is_call = (
            (payload.get("call_id") and payload.get("message"))
            or payload.get("TYPE") == "24"
            or notif_type == "bell"
        )
        if not is_call:
            _LOGGER.debug("Push not a call, ignoring: %s", _redact(payload))
            return
        call_id = payload.get("call_id") or payload.get("NOTIFICATION_UUID")
        if not call_id:
            _LOGGER.debug(
                "Call push without identifier, ignoring: %s", _redact(payload)
            )
            return

        # If a previous call is still tracked (mid-call, or in the 60 s
        # post-BYE grace window kept alive for late HomeKit hub pulls), the
        # fresh push always wins: the Intratone server has rotated the SIP
        # dialog and the old credentials are stale. Tear it down now so the
        # subsequent ensure_call_started() isn't blocked by the
        # "Call already active" guard in CallManager.start_call.
        if (
            self._call_manager is not None
            and self._call_manager.active_call_id is not None
        ):
            _LOGGER.info(
                "New ring while previous call %s still tracked — aborting it",
                self._call_manager.active_call_id,
            )
            await self._call_manager.abort_active_call()

        self._ring_seq += 1
        state = CallState(
            call_id=str(call_id),
            door_name=payload.get("message") or "Doorbell",
            caller_login=payload.get("LOGIN_TO_CALL", ""),
            received_at=datetime.now(UTC),
            ring_seq=self._ring_seq,
            door_code=payload.get("codes") or "*",
            door_number=payload.get("NBPORTE", ""),
        )
        _LOGGER.info(
            "Doorbell ring: door=%s call_id=%s seq=%d (SIP deferred)",
            state.door_name,
            state.call_id,
            state.ring_seq,
        )

        # Park the SIP creds; pending dispatch on first user interaction.
        sip_target_user = payload.get("LOGIN_TO_CALL")
        sip_user = payload.get("LOGIN")
        sip_pass = payload.get("PASS")
        sip_server_ip = payload.get("ip_adress") or payload.get("domain_sip")
        if all((sip_target_user, sip_user, sip_pass, sip_server_ip)):
            self._pending = _PendingInvite(
                fcm_call_id=str(call_id),
                target_uri=f"sip:{sip_target_user}@{sip_server_ip}",
                target_host=sip_server_ip,
                sip_username=sip_user,
                sip_password=sip_pass,
            )
        else:
            _LOGGER.debug(
                "Push missing SIP creds; lazy INVITE will be skipped on tap"
            )
            self._pending = None

        # Fire the HomeKit doorbell event (ring on iPhone).
        self.async_set_updated_data(state)

    async def async_ensure_call_started(self) -> bool:
        """Trigger the SIP INVITE on first user interaction (live view or
        unlock tap). Idempotent: subsequent calls within the same ring just
        wait on the existing `stream_ready` event.

        Returns True if a call is started (or already was), False if there
        are no pending creds or the call manager is missing.
        """
        if self._pending is None or self._call_manager is None:
            return False
        pending = self._pending
        if pending.started:
            return True
        pending.started = True

        _LOGGER.info(
            "User interaction → starting SIP INVITE for FCM call %s",
            pending.fcm_call_id,
        )
        try:
            self._active_sip_call_id = await self._call_manager.start_call(
                target_uri=pending.target_uri,
                target_host=pending.target_host,
                sip_username=pending.sip_username,
                sip_password=pending.sip_password,
            )
        except Exception:  # noqa: BLE001
            _LOGGER.exception("Failed to initiate SIP call")
            return False

        # Tell Intratone "user picked up" — matches the Cogelec app, which
        # calls /answer on the `Connected` SIP state. We fire it in parallel
        # with the INVITE; the server processes both fine.
        if not pending.answer_called:
            pending.answer_called = True
            try:
                picked_up = await self.api.answer_call(pending.fcm_call_id)
                if picked_up:
                    _LOGGER.debug(
                        "Call %s marked as picked up", pending.fcm_call_id
                    )
            except Exception:  # noqa: BLE001
                _LOGGER.warning("informCallPickedUp failed", exc_info=True)
        return True

    async def async_wait_for_stream(self, timeout: float = _STREAM_READY_TIMEOUT_S) -> str | None:
        """Wait up to `timeout` seconds for the audio bridge to be up, then
        return the RTSP stream URL. Used by the camera entity in HomeKit's
        stream_source path.

        On timeout we return None but keep the SIP dialog alive — the user
        can still tap Unlock during the call window even if the camera pull
        failed, and a subsequent camera tap will retry on the same bridge.
        """
        if self._pending is None:
            return self.data.stream_url if self.data else None
        try:
            await asyncio.wait_for(self._pending.stream_ready.wait(), timeout=timeout)
        except asyncio.TimeoutError:
            _LOGGER.warning("Stream not ready within %ss", timeout)
            return None
        return self.data.stream_url if self.data else None

    @callback
    def set_stream_url(self, sip_call_id: str, url: str | None) -> None:
        """Update the active call's stream URL (called by CallManager callbacks).

        Matches against the tracked SIP call_id (NOT the FCM `call_id` exposed
        to /answer), so a stale call_established after a fast hang-up is
        ignored. When `url` is None we also clear the tracker AND the pending
        invite (next ring will need a fresh user tap to start).
        """
        if self.data is None or self._active_sip_call_id != sip_call_id:
            return
        if url is None:
            self._active_sip_call_id = None
            if self._pending is not None:
                self._pending.stream_ready.clear()
                self._pending = None
        else:
            if self._pending is not None:
                self._pending.stream_ready.set()
        if self.data.stream_url == url:
            return
        self.async_set_updated_data(dataclasses.replace(self.data, stream_url=url))

    async def async_open_door(self) -> bool:
        """Send `opendoor:<code>` as an in-dialog SIP MESSAGE.

        If the user taps Unlock without having opened live view first, we
        first kick off the SIP call (lazy INVITE) and wait briefly for it to
        confirm. Then we send the MESSAGE.
        """
        if self.data is None:
            _LOGGER.warning("Open door requested but no active call known")
            return False
        if self._call_manager is None:
            _LOGGER.warning("Open door requested but no call manager attached")
            return False

        # Lazy: start the SIP call if the user is jumping straight to unlock.
        if self._pending is not None and not self._pending.started:
            await self.async_ensure_call_started()
            # Wait for the bridge to be up before sending the MESSAGE — needs
            # the dialog to be CONFIRMED (200 OK received + ACK sent).
            await self.async_wait_for_stream()

        door_opened = self._call_manager.send_open_door(self.data.door_code)

        if door_opened:
            _LOGGER.info(
                "Door opened for call %s (code=%s)",
                self.data.call_id,
                self.data.door_code,
            )
        else:
            _LOGGER.warning(
                "Open door failed for call %s — no confirmed SIP call to send "
                "MESSAGE in (call may have BYE'd already)",
                self.data.call_id,
            )
        return door_opened

    async def async_toggle_backlight(self) -> bool:
        """Send the in-dialog `contrast` SIP MESSAGE.

        Asks the doorbell hardware to enable backlight mode (front
        illuminator / high-gain camera mode) for the rest of the call.
        Server resets the state on BYE so this only has effect while the
        SIP dialog is up. Lazy-starts the call if the user toggles before
        opening the camera view.
        """
        if self.data is None or self._call_manager is None:
            return False
        if self._pending is not None and not self._pending.started:
            await self.async_ensure_call_started()
            await self.async_wait_for_stream()
        return self._call_manager.send_backlight()

    async def _async_handle_call_cancel(self, payload: dict) -> None:
        """Visitor walked away before pickup — abort any in-flight call so a
        stale stream URL won't be served and the next FCM ring can start
        fresh without waiting on the BYE grace window."""
        canceled_id = payload.get("call_id") or payload.get("NOTIFICATION_UUID")
        _LOGGER.info("Received callCancel push for call %s", canceled_id)
        if (
            self._call_manager is not None
            and self._call_manager.active_call_id is not None
        ):
            await self._call_manager.abort_active_call()
        self._pending = None


_REDACT_KEYS = {"LOGIN", "PASS", "ip_adress"}


def _redact(payload: dict) -> dict:
    """Mask sensitive fields when logging FCM payloads."""
    return {k: ("***" if k in _REDACT_KEYS else v) for k, v in payload.items()}
